### PR TITLE
Steven codesnip

### PR DESCRIPTION
**Pull request by stevens34400**
- Created a new team model
- added name under tournament model

### CODE REVIEW

**Comment by stevens34400** [comment]
- Rough idea for the search tab, currently only bases search off of object's "name"

**Comment by akp5896** [comment]
Looks great, but for this lines:
postQuery.include(Post.author);
I thought "include" is used only for pointers?

**Comment by stevens34400** [comment]
Just updated the include() statements

**Review by akp5896 — APPROVED** [review]

**Comment by justin212553** [comment]
Looks good

**Pull request merged**
